#!/usr/bin/env node

const {Client} = require('tplink-smarthome-api');

// argv[0]: /path/to/node
// argv[1]: /path/to/this/script
// argv[2]: ip.address.of.target.device
// argv[3]: on|off|0|1
const host = process.argv[2];
const stateName = process.argv[3];

var state;
switch (stateName.toLowerCase()) {
case 'on':
case '1':
  state = true;
  break;
case 'off':
case '0':
  state = false;
  break;
default:
  console.error('Unknown state name:', stateName);
  process.exit(1);
}

const client = new Client();
client.getDevice({host}).then(device => {
  device.setPowerState(state);
}).catch(error => {
  console.error(error);
  process.exit(1);
});
